name: jadwal_solat
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  date_picker_timeline: ^1.2.5
  easy_date_timeline: ^1.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter  
  flutter_screenutil: ^5.9.0
  flutter_svg: ^1.1.5
  get_it: ^7.6.7
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  http: ^1.2.0
  iconify_flutter: ^0.0.4
  internet_connection_checker_plus: ^2.2.0
  intl: ^0.18.1
  meta: ^1.10.0
  mocktail: ^1.0.3
  persistent_bottom_nav_bar: ^5.0.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0


flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Black.ttf
          weight: 900
        - asset: assets/font/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Poppins-Thin.ttf
          weight: 100
